### ISSUE TITLE
Can't find any settings that work to remove burst of clipping static (example .wav attached)

### ISSUE THREAD

**Issue by enn-nafnlaus** [timsainb/noisereduce#81]
Notice the burst of clipping static at the beginning.  All settings I've tried either do nothing to the static or obliterate the audio.

Since github doesn't allow .wav files to be attached, I've renamed it a .zip; just rename the extension.
[bell.zip](https://github.com/timsainb/noisereduce/files/11255032/bell.zip)

**Comment by nuniz** [comment]
Hi,
The spectral gating algorithm is not effective for de-clipping audio. I recommend looking into other algorithms or code for this task.

If you recorded the audio, it is likely that the clipping is due to the analog parts of the microphone or amplifiers, rather than the ADC. In this case, you may be able to reduce the clipping by reducing the gain.

Best,
Asaf
