### ISSUE TITLE
Latency for streaming audio

### ISSUE THREAD

**Issue by mukundt** [timsainb/noisereduce#91]
Hey there! Thanks again for creating this awesome library :) Quick question about latency. I'm using noisereduce on audio packets that are 8Khz, 32ms in length each. On my M1 Mac, running noisereduce on each audio packet takes ~10ms. When running on AWS EC2 (4 CPUs) however, running noisereduce on each audio packet takes ~40ms. Is this expected behavior or am I doing something wrong?

```
audio_int8 = nr.reduce_noise(
                    y=audio_int8,
                    sr=8000,
                    n_fft=128,
                    stationary=False,
                    n_jobs=-1,
                    chunk_size=600000 * 3,
                )
```

**Comment by timsainb** [comment]
Hey Mukundt, 

I haven't spent much time benchmarking, but if you are using the most recent version on pytorch, you will see a significant speedup (10x) on a gpu. Otherwise, parts of the code are parallelized, so it is not surprising that your M1 mac is a lot faster than a 4 core cpu AWS node. You can try looking at htop or similar to see where your bottleneck is.
